services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/credentials.json:/app/credentials.json
    ports:
      # Buka port backend ke server
      - "1412:1412"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      # Buka port frontend ke server
      - "1413:80"
