services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/credentials.json:/app/credentials.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  proxy:
    image: nginx:1.25-alpine
    restart: always
    ports:
      # Kita gunakan port 1400 untuk aplikasi presensi kita
      - "1400:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
