services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: presence-backend
    ports:
      - "1412:1412" # Host:Container port
    networks:
      - app-network
    volumes:
      - ./backend/credentials.json:/app/credentials.json:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: presence-frontend
    ports:
      - "5174:3000" # Host:Container → kita pilih host port 5174 yang masih kosong
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    # env_file:

networks:
  app-network:
    driver: bridge
