services:
  # Layanan Backend (Aplikasi Go)
  backend:
    build:
      context: ./backend # Path sekarang relatif dari root
      dockerfile: Dockerfile
    restart: always
    volumes:
      # Hubungkan credentials.json dari root ke dalam container
      - ./backend/credentials.json:/app/credentials.json
    ports:
      # Gunakan port 1400 di server (STB) Anda
      - "1412:1412"

  # Layanan Frontend (Nginx + SvelteKit)
  frontend:
    build:
      context: ./frontend # Path sekarang relatif dari root
      dockerfile: Dockerfile
    restart: always
    ports:
      # Gunakan port 1400 di server (STB) Anda
      - "1413:80"
